//
//  NSPasteboard.PasteboardType+Extensions.swift
//  Clipchop
//
//  Created by KrLite on 2024/4/28.
//

import Foundation
import AppKit

// Code from https://github.com/p0deje/Maccy
extension NSPasteboard.PasteboardType {
    static let jpeg = NSPasteboard.PasteboardType(rawValue: "public.jpeg")
    static let universalClipboard = NSPasteboard.PasteboardType(rawValue: "com.apple.is-remote-clipboard")
    
    // See http://nspasteboard.org for more details.
    static let autoGenerated = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")
    static let concealed = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")
    
    // https://github.com/p0deje/Maccy/issues/429#issuecomment-1182575226
    static let modified = NSPasteboard.PasteboardType(rawValue: "x.nspasteboard.ModifiedType")
    
    // Types that indicate Microsoft Word bookmarks (links).
    // https://github.com/p0deje/Maccy/issues/613
    static let microsoftObjectLink = NSPasteboard.PasteboardType(rawValue: "com.microsoft.ObjectLink")
    static let microsoftLinkSource = NSPasteboard.PasteboardType(rawValue: "com.microsoft.Link-Source")
}

extension NSPasteboard.PasteboardType {
    static let fromClipchop = NSPasteboard.PasteboardType(rawValue: "studio.nnn.Clipchop")
}
